// #define main 1
// #define identifier 2
// #define constant 3
// #define define 4
// #define Integer 5
// #define Char 6
// #define while 7
// #define for 8
// #define if 9
// #define else 10
// #define in.Integer 11
// #define in.Chars 12
// #define out 13